FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:gophers/archive
RUN apt update
RUN apt install -y git curl
RUN apt install -y golang-1.10-go
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/go-1.10/bin:/go/bin
ENV GOPATH=/go
ENV TF_TYPE=gpu
ENV TF_DIR=/usr/local
RUN mkdir -p /go/src

RUN go get -u github.com/kardianos/govendor
RUN git clone https://github.com/tensorflow/tensorflow /tensorflow
WORKDIR /tensorflow
RUN git checkout v1.8.0

RUN apt-get update && apt-get install -y --no-install-recommends \
      python-dev

RUN echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
RUN curl https://bazel.build/bazel-release.pub.gpg |  apt-key add -
RUN apt-get update &&  apt-get install -y bazel

ENV TF_NEED_CUDA 1
ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.0,6.1
ENV TF_NEED_MKL 1
# easiest to build against its own version
ENV TF_DOWNLOAD_MKL 1

#RUN yes "" | ./configure
RUN apt-get install -y patch
RUN tensorflow/tools/ci_build/builds/configured GPU
RUN bazel build --config=mkl --config=cuda --config=opt --config=monolithic //tensorflow:libtensorflow.so
RUN cp bazel-bin/tensorflow/libtensorflow.so /usr/local/lib
RUN cp /root/.cache/bazel/_bazel_root/*/external/mkl_linux/lib/* /usr/local/lib
RUN ldconfig
RUN ln -s /tensorflow/tensorflow /usr/local/include/tensorflow
